# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a8316e2f0200bb51933eaf3adc0cdf844adfeac8db7206f62e6d7fe0fb2d78d0d5d5cb7bc8e163f76983fd1f944f83ce8136064b663929d03bdc63ea8d60665

test:
  secret_key_base: 6ee5ef87334920dca291b2a32f9a46ad87a15b99f46a4ebdf4860b1e172a2e07e2ca92eec2c9dcb291a28fb374171cf56dfa51381ddfa20aa6cd6f095b3bba85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
